### ISSUE TITLE
features I would like to see in this software - Contact me regarding 

### ISSUE THREAD

**Issue by theancients89** [IBM/speech-to-text-code-pattern#81]
Could someone contact me please with regards to some features I'd like to integrate into my existing systems? I would appreciate a bit of help in what is a straightforward need.

You can contact me - via http://simplefixit.co.uk if that helps!

**Comment by 1154046** [comment]
@theancients89 did you get help with this, if not, I would like to help.

**Comment by 1154046** [comment]
Yes, please send me an email - Sbusiso.Mkhombe@ibm.com and we can discuss further ?
